dist: focal
language: generic
services:
  - docker

stages:
  - name: linting

jobs:
  include:
    - stage: "linting"
      name: "pydocstyle"
      script:
        - pip install pydocstyle
        - pydocstyle .
