dist: focal
language: generic
services:
  - docker

stages:
  - name: linting

jobs:
  include:
    - stage: "linting"
      name: "pydocstyle"
      script:
        - pip install pydocstyle
        - pydocstyle .

    - stage: "linting"
      name: "flake8"
      script:
        - pip install flake8
        - flake8 .

    - stage: "linting"
      name: "code complexity"
      script:
        - flake8 --max-complexity 10 .
