dist: focal
language: generic
services:
  - docker

stages:
  - name: linting

jobs:
  include:
    - stage: "linting"
      name: "Linting"
      install:
        - pip install pydocstyle
        - pip install flake8
      script:
        - pydocstyle .
        - flake8 .
        - flake8 --max-complexity 10 .
