dist: focal
language: generic
services:
  - docker

env:
  global:
    - COMMIT_HASH=$(git rev-parse HEAD)
    - DOCKER_TAG=${COMMIT_HASH}
    - DOCKER_REPO="160digital/test-tn-backend"
    - DOCKER_IMAGE=${DOCKER_REPO}:${DOCKER_TAG}

stages:
  - name: static_analysis

jobs:
  include:
    - stage: "static_analysis"
      name: "pydocstyle"
      script:
        - docker run --rm -v $(pwd):/data cytopia/pydocstyle .
